theme: jekyll-theme-slate
title: Will Oldroyd, PhD
description: "Sr. Astrodynamics Engineer, SDA<br/>Katalyst Space Technologies,<br/>Researcher<br/>Northern Arizona University<br/>Department of Astronomy and Planetary Science"
